name = "story_bakery/extended_translator"
version = "0.1.0"
license = "MIT"
includes = ["pesde.toml", "LICENSE", "README.md", ".pesde/scripts/roblox_sync_config_generator.luau", ".pesde/scripts/sourcemap_generator.luau", "src/**/*.luau", "src/**/*.json", "tests/**/*.luau"]

[target]
environment = "roblox"
lib = "src/ExtendedTranslator.luau"
build_files = [
    "src",
]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
Signal = { repo = "Story-Bakery/Signal", rev = "main" }
Maid = { repo = "Story-Bakery/Maid", rev = "main" }

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
